### PR TITLE
Split reports by core project

### PR DESCRIPTION
**Pull request by vincerubinetti**
Changes roughly in order of diff:

- add test workflow. simplify and make use of root-level run script.
- elaborate readmes
- add logo and favicon
- update package versions
- add vue router
- add some icons
- add some basic components, including table with tanstack table
- generate more data json files for app
- add dedicated page for each core project with basic info and table of publication details
- add listing of core projects
- add some global/total stats to homepage
- style tweaks, including more print styles 
- lift certain important paths/vars up into .env file
- make pipeline more modular and flexible. split up into different steps/files/folders. more consistent process. env vars for important switches. open preview for each step.
- add root-level run script to conveniently run commands

### CODE REVIEW

**Comment by cgreene** [comment]
This looks to move totally to project-level reporting. Will we lose the program-level dashboard with this? I think we must do the project-level reporting, but it was nice having the quick snapshot at the program level.

**Comment by vincerubinetti** [comment]
There are some CFDE-total stats on the home page. Before this PR I had some pie charts like the breakdown of project number prefixes. I got rid of those here since it was just placeholder visualization and I figured that wasn't useful information. I can add it back in or any other program level info that you think is useful.

**Comment by vincerubinetti** [comment]
Hopefully I'm understanding "program level" right. Perhaps it is actually "opportunity numbers". Either way, I think things are set up to pretty quickly add whatever data I have access to at any level you want in this PR.

**Review by seandavi — CHANGES_REQUESTED** [review]
I like the information content associated with this approach. I'd suggest adding some semblance of an "award title" to the project page just to make it easier to find projects of interest. You might also add the "award mechanism code" (OTA, R03, etc.) as a column on the first page as well. Our main audience will be NIH folks at this point, so giving those couple of details as top level could help them identify their respective programs/projects.

**Review by cgreene — APPROVED** [review]

**Pull request merged**
